# Generated by Django 4.1.7 on 2023-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=150)),
            ],
        ),
    ]
