# Generated by Django 4.1.7 on 2023-03-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_alugel', models.DateField()),
                ('data_entrega', models.DateField()),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.cliente')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.carro')),
            ],
        ),
    ]
