# Generated by Django 4.1.7 on 2023-03-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_remove_carro_id_remove_cliente_id_alter_carro_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.CharField(max_length=7),
        ),
    ]
